### ISSUE TITLE
Cover all scenarios through Docker

### ISSUE THREAD

**Issue by Kostov6** [gardener/website-generator#238]
**What would you like to be added**:
Those are the scenarios we would like to cover:
- Local development 
  - provide docforge config (through volume mount) https://github.com/gardener/website-generator/pull/241
  - provide local manifest (docforge config) https://github.com/gardener/website-generator/pull/243
  - provide resourceMappings (docforge config and volume mounts) https://github.com/gardener/website-generator/pull/243
  - exporting website to localhost and browse it through the browser (through port mount) https://github.com/gardener/website-generator/pull/240
- CI/CD
  - consume docforge config (through `DOCFORGE_CONFIG`) https://github.com/gardener/website-generator/pull/242
  - export website build result https://github.com/gardener/website-generator/pull/245

One way to achieve this is through Docker compose

**Why is this needed**:
- Only the maintenance of the compose files and the Dockerfile will be necessary 
- Non-os dependent execution
- Execution of a scenario will only require configuration of a Docker compose file and running `docker compose` or a normal `docker run` command

**Subtasks:**
- [x] https://github.com/gardener/website-generator/pull/240
- [x] https://github.com/gardener/website-generator/pull/241
- [x] https://github.com/gardener/website-generator/pull/242
- [x] https://github.com/gardener/website-generator/pull/243

**Comment by dimitar-kostadinov** [comment]
The listed point fully cover the local development scenario.
