### ISSUE TITLE
Migrate gardener.cloud to docsy theme

### ISSUE THREAD

**Issue by Kristian-ZH** [gardener/website-generator#80]
**Why is this needed**:
As we have discussed, the default theme should be switched to Docsy, because most of the features we want to implement,
are already existing in Docsy.

**Changes needed to be done before switching to Docsy**:
- [x] Update docforge manifest with reorganised blogs.
   - [x] Sort blogs by date (latest on top).
   - [x] Do not use section files.
- [x] Make adopters page in Markdown format
- [x] Remove home folder from the content
- [x] Integrate a search field
- [x] Remove `type` field from the frontmatter
- [x] Handle docsy submodule in the CI/CD
- [x] Add documentation for the .gitmodules
